"""Add last_status to monitoring_sources

Revision ID: 21349ec1bb04
Revises: 8798003efbda
Create Date: 2026-01-31 19:50:33.659597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21349ec1bb04'
down_revision: Union[str, None] = '8798003efbda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoring_sources', sa.Column('last_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitoring_sources', 'last_status')
    # ### end Alembic commands ###
